### ISSUE TITLE
If listen == false, output[k] doesnt change

### ISSUE THREAD

**Issue by Darth-Carrotpie** [zombience/audio_analyzer#3]
Apparently, "listen" bool is meant to disable sound playback, while still keeping the recording and analysis. Am I right? Sadly, it does not work like that. If you untick the option, objects in test scene stop reacting.

**Comment by zombience** [comment]
fixed in an update.
unity updated the way that AudioSource works, so that if an AudioSource volume is 0 (muted) no audio will be processed.
I moved that functionality over to a mixer group. So now mixer groups must be assigned properly in the inspector. 

I've updated the test scene. Let me know if anything else becomes an issue.
